"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$python\
$rust\
$golang\
$nodejs\
$docker_context\
$kubernetes\
$line_break\
$character"""

right_format = """
$time\
"""

[directory]
style = "bold blue"
read_only = " 󰌾"
read_only_style = "bold red"
home_symbol = "~"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"
truncation_length = 20
truncation_symbol = "…"

[git_status]
style = "bold red"
stashed = " "
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = " "
staged = " "
modified = " "
renamed = " "
deleted = " "
conflicted = " "
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[python]
disabled = false
symbol = " "
format = "[$symbol$version]($style) "
style = "bold yellow"
pyenv_version_name = true

[rust]
disabled = false
symbol = " "
format = "[$symbol$version]($style) "
style = "bold orange"

[golang]
disabled = false
symbol = " "
format = "[$symbol$version]($style) "
style = "bold cyan"

[nodejs]
disabled = false
format = "[$symbol$version]($style) "
symbol = " "
style = "bold green"

[docker_context]
disabled = false
symbol = " "
format = "[$symbol$context]($style) "
style = "bold bright-blue"

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '[$symbol$context(::$namespace)]($style) '
style = "bold magenta"

[time]
disabled = false
style = "dimmed white"
format = "[$time]($style) "
time_format = "%T"
use_12hr = false

[gcloud]
disabled = true
format = ""

[cmd_duration]
disabled = true
format = ""

[aws]
disabled = true
format = ""

[username]
disabled = true
show_always = false
format = ""

[hostname]
disabled = true
ssh_only = true
format = ""

[shell]
disabled = true
format = ""

[jobs]
disabled = true
format = ""
